#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
#  Portions of this software are Copyright (c) 2023-2024 HPC-Gridware GmbH
#
##########################################################################
#___INFO__MARK_END__

# define global variable in this namespace
global check_name 
global check_category 
global check_description 
global check_needs
global check_functions 
global check_root_access_needs
global check_need_running_system

set check_root_access_needs "yes"

# define test's name and run level descriptions
set check_name            "jemalloc_test"
set check_category        "COMPATIBILITY SYSTEM QHOST QQUOTA VERIFIED"
set check_description(0)  "basic test if compiled with jemalloc"

# define test's procedure order
set check_functions {}
lappend check_functions "jemalloc_verify"

# -------- local test procedures: initialization------------------------------

proc jemalloc_verify {} {
   global ts_config CHECK_USER
 
   # binaries to test
   # @todo should we better build the list dynamically?
   # @todo also test utilbin and jobsbin binaries?
   set binaries "qacct qconf qmod qping qrdel qrls qrstat qselect qstat sge_execd sge_qmaster sge_shepherd qalter qdel qhost qquota qresub qrsh qrsub qsh qsub sge_coshepherd sge_shadowd"

   # we use jemalloc only on lx-amd64
   # @todo extend test when we link it on other archs as well
   foreach arch {"lx-amd64"} {
      # we call strings on the compile host
      set jemalloc_test_host [compile_search_compile_host $arch]
      set errors {}

      foreach binary $binaries {
         ts_log_fine $binary
         set binpath "$ts_config(product_root)/bin/lx-amd64/$binary"
         set output [start_remote_prog $jemalloc_test_host "root" "strings" $binpath]

         if {[string first "<jemalloc>" $output] < 0} {
            lappend errors "$binpath does not contain \"<jemalloc>\""
            ts_log_fine $output
         }
      }
      if {[llength $errors] > 0} {
         ts_log_severe [join $errors "\n"]
      }
   }
}
