#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
#  Portions of this software are Copyright (c) 2011 Univa Corporation.
#
#  Portions of this software are Copyright (c) 2024 HPC-Gridware GmbH
#
##########################################################################
#___INFO__MARK_END__

# Define the global variables to give them back
global check_name check_description check_needs check_functions
global check_category
global ts_config
global check_root_access_needs
set check_root_access_needs "yes"

# set description for each level
set check_description(0)  "check qsub -t option"

set check_name         "qsub_t"
set check_category     "COMPATIBILITY SYSTEM L10N EVENTCLIENT VERIFIED"
set check_needs        "init_core_system"       ;# dependencies of this check (name of other check)

# setup and cleanup functions
set check_setup_function "qsub_setup"
set check_cleanup_function "qsub_cleanup"

# define test's procedure order
set check_functions {}
lappend check_functions "qsub_t"
lappend check_functions "qsub_t_iz_145" ; # Testcase for TS IZ 145

proc qsub_setup {} {
   global ts_config
   global CHECK_JOB_OUTPUT_DIR
   global stored_configuration
   global job_output_dir test_host default_args default_q_args default_h_args
   global steps_per_queue size_interval

   # set some global variables
   set num_queues [llength $ts_config(unique_arch_nodes)] 
   set job_output_dir $CHECK_JOB_OUTPUT_DIR

   # run host specific tests on a random host
   set test_host [host_conf_get_suited_hosts]

   # set default jobargs
   set default_args "-o $job_output_dir -e $job_output_dir $ts_config(product_root)/examples/jobs/sleeper.sh 5"
   set qinstance [get_queue_instance "all.q" $test_host]
   set default_q_args "-q $qinstance $default_args"
   set default_h_args "-l h=${test_host} $default_args"

   # backup global config
   get_config stored_configuration
  
   # set config for fast scheduling / fast writing of accounting record
   set my_config(reporting_params) "accounting=true reporting=false flush_time=00:00:01 joblog=true sharelog=00:10:00"
   set_config my_config
}

proc qsub_cleanup {} {
   global ts_config
   global stored_configuration
   global job_output_dir test_host default_args default_q_args default_h_args
   global steps_per_queue size_interval

   set spool_dir [get_spool_dir $ts_config(master_host)  "qmaster"] 
   if {[is_qmaster_alive $ts_config(master_host) $spool_dir] != 1} {
      if {[is_scheduler_alive $ts_config(master_host) $spool_dir] != 1} {
         startup_qmaster 1
      } else {
      startup_qmaster 0
      }
   }

   delete_all_jobs
   wait_for_end_of_all_jobs

   reset_config stored_configuration

   # unset our test global variables
   foreach var "stored_configuration job_output_dir test_host default_args default_q_args default_h_args steps_per_queue size_interval" {
      if {[info exists $var]} {
         unset $var
      }
   }
}

proc qsub_submit_check {jobargs expect_submit_error {user ""} {host ""} {output_files 2}} {
   global ts_config CHECK_FIRST_FOREIGN_SYSTEM_USER
   global job_output_dir

   # default user is the first "foreign" user!
   if {$user == ""} {
      set user $CHECK_FIRST_FOREIGN_SYSTEM_USER
   }

   # default submit host is "any host"
   if {$host == ""} {
      set host [host_conf_get_suited_hosts]
   }

   # if we expect a submit error, submit_job shall not do error checking
   set submit_error_check 1
   if {$expect_submit_error} {
      set submit_error_check 0
   }

   # submit job and evaluate result
   set job_id [submit_job $jobargs $submit_error_check 60 $host $user]
   if {$expect_submit_error} {
      if {$job_id > 0} {
         ts_log_severe "submission of job \"$jobargs\" as user $user on host \"$host\" should have failed"
         delete_job $job_id
      }
      # are done
      return 0
   } else {
      if {$job_id < 0} {
         ts_log_severe "submission of job \"$jobargs\" as user $user on host \"$host\" failed:\nerror $job_id"
         return 0
      }
   }

   # wait for job accounting record and expect 1 or 2 ($output_files) output/error files
   set time [expr [timestamp] + 300] 
   while {[timestamp] < $time}  {
      after 1000
      set back [was_job_running $job_id 0]
      if {$back != -1} {
         set back [del_job_files $job_id $job_output_dir $output_files]
         if {$back != $output_files} {
            ts_log_severe "job $job_id (\"$jobargs\") did not produce error and output file"
            return 0
         } else {
            # job ran through successfully
            return $job_id
         }
      }
   }

   # if we get here, we didn't find an accounting record within reasonable time
   ts_log_severe "timeout waiting for job $job_id (\"$jobargs\")"

   # cleanup
   delete_job $job_id
   del_job_files $job_id $job_output_dir 2
   return 0
}
 
proc check_submit {} {
   global ts_config
   global default_args

   # first clean up output directory:
   setup_output_directory
   
   # submit from every architecture
   foreach host $ts_config(unique_arch_nodes) {
      ts_log_fine "--> submit on host $host"
      qsub_submit_check $default_args 0 "" $host
   }

   # submit to every architecture
   foreach host $ts_config(unique_arch_nodes) {
      ts_log_fine "--> submit to host $host"
      qsub_submit_check "-l h=${host} $default_args" 0
   }
}

proc qsub_t {} {
   global ts_config
   global default_args

   # first clean up output directory:
   setup_output_directory

   # positive tests
   set option "-t 2-8:2"
   set jobargs "$option $default_args"
   qsub_submit_check $jobargs 0 "" "" 8
 
   # negative test:
   set option "-t 1-2:-1"
   set jobargs "$option $default_args"
   qsub_submit_check $jobargs 1

   set option "-t 1-2:xx"
   set jobargs "$option $default_args"
   qsub_submit_check $jobargs 1

   set option "-t 1-500000"
   set jobargs "$option $default_args"
   qsub_submit_check $jobargs 1
}

#****** qsub/qsub_t_iz_145() ***********************************************
#  NAME
#     qsub_t_iz_145() -- Testcase for TS IZ 145.
#
#  SYNOPSIS
#     1. Run qsub -t 1-100:100 -cwd sleep.sh
#     2. Check that  the output file looks correct
#        This file will be in the local dir, called
#        sleep.sh.o<jobid>.1
#     3 Repeat for qsub -t 1-95:100 -cwd sleep.sh
#     4.Repeat for qsub -t 1-100:50 -cwd sleep.sh
#        In this case, we have TWO output files,
#        sleep.sh.o<jobid>.1 and sleep.sh.o<jobid>.51
#     5. Repeat for qsub -t 1-100:50 -cwd sleep.sh
#
#  FUNCTION
#     Check if TS IZ 145 has been fixed.
#  INPUTS
#
#*******************************************************************************
proc qsub_t_iz_145 {} {

   # Call with -t 1-100:100
   set SGE_TASK_FIRST 1
   set SGE_TASK_LAST 100
   set SGE_TASK_STEPSIZE 100

   qsub_ts_iz_145 $SGE_TASK_FIRST $SGE_TASK_LAST $SGE_TASK_STEPSIZE

   # Call with -t 1-95:100
   set SGE_TASK_FIRST 1
   set SGE_TASK_LAST 95
   set SGE_TASK_STEPSIZE 100

   qsub_ts_iz_145 $SGE_TASK_FIRST $SGE_TASK_LAST $SGE_TASK_STEPSIZE

   # Call with -t 1-100:50
   set SGE_TASK_FIRST 1
   set SGE_TASK_LAST 100
   set SGE_TASK_STEPSIZE 50

   qsub_ts_iz_145 $SGE_TASK_FIRST $SGE_TASK_LAST $SGE_TASK_STEPSIZE

   # Call with -t 1-95:50
   set SGE_TASK_FIRST 1
   set SGE_TASK_LAST 95
   set SGE_TASK_STEPSIZE 50

   qsub_ts_iz_145 $SGE_TASK_FIRST $SGE_TASK_LAST $SGE_TASK_STEPSIZE
}

proc qsub_ts_iz_145 { {t_sge_task_first "1"} {t_sge_task_last "4"}
                      {t_sge_task_stepsize "4" } } {
   global ts_config env
   global CHECK_USER CHECK_ACTUAL_TEST_PATH

   set SGE_TASK_FIRST $t_sge_task_first
   set SGE_TASK_LAST $t_sge_task_last
   set SGE_TASK_STEPSIZE $t_sge_task_stepsize

   set host $ts_config(master_host)
   set output_tmpfile [get_tmp_file_name]

   # Delete any remaining jobs
   delete_all_jobs

	#1. First submit
   set job_id [submit_job "-t $SGE_TASK_FIRST-$SGE_TASK_LAST:$SGE_TASK_STEPSIZE -o $output_tmpfile -e /dev/null $CHECK_ACTUAL_TEST_PATH/step.sh"]
   trigger_scheduling

   # Sleep until the jobs are finished
   wait_for_jobend $job_id "step" 10 0

   set result [start_remote_prog $host $CHECK_USER cat $output_tmpfile exit_code]
   # echo first $SGE_TASK_FIRST last $SGE_TASK_LAST step $SGE_TASK_STEPSIZE
   # ts_log_fine "result is \n $result"

   if {$exit_code != 0 || $result == ""} {
      ts_log_severe "error reading from output file on host $host:\n$result"
   } else {
      if {[scan $result "first  %d last %d step %d" sge_task_first sge_task_last sge_task_stepsize] != 3 } {
         ts_log_severe "error parsing output file from host $host:\n$result"
      } else {
         # sge_task_first should be $SGE_TASK_FIRST
         if {$sge_task_first != $SGE_TASK_FIRST} {
            ts_log_severe "SGE_TASK_FIRST is incorrect:\n$sge_task_first, expected $SGE_TASK_FIRST"
         } else {
            ts_log_fine "SGE_TASK_FIRST is $sge_task_first \n"
         }

         # sge_task_last should be $SGE_TASK_LAST
         if {$sge_task_last != $SGE_TASK_LAST} {
            ts_log_severe "SGE_TASK_LAST is incorrect:\n$sge_task_last, expected $SGE_TASK_LAST"
         } else {
            ts_log_fine "SGE_TASK_LAST is $sge_task_last \n"
         }

         # sge_task_stepsize should be $SGE_TASK_STEPSIZE
         if {$sge_task_stepsize != $SGE_TASK_STEPSIZE} {
            ts_log_severe "SGE_TASK_STEPSIZE is incorrect:\n$sge_task_stepsize, expected $SGE_TASK_STEPSIZE"
         } else {
            ts_log_fine "SGE_TASK_STEPSIZE is $sge_task_stepsize \n"
         }
      }
   }

   #clean up
   file delete $output_tmpfile
}
